version: '3.8'

services:
  cloudsearch-backend:
    image: "102153735617.dkr.ecr.ap-southeast-1.amazonaws.com/cloudsearch-sample-backend:solo"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "80:8000"