GOOGLE_PROJECT_ID=<PROJECT_ID>
CLOUD_RUN_SERVICE=<CLOUD_RUN_SERVICE>
INSTANCE_CONNECTION_NAME=<DATABASE_CONNECTION_NAME>
DB_USER=<DATABASE_USER>
DB_PASS=<DATABASE_PASSWORD>
DB_NAME=<DATABASE_NAME>

# gcloud builds submit --tag gcr.io/$GOOGLE_PROJECT_ID/$CLOUD_RUN_SERVICE --project=$GOOGLE_PROJECT_ID
# gcloud run deploy $CLOUD_RUN_SERVICE \
# 	--image gcr.io/$GOOGLE_PROJECT_ID/$CLOUD_RUN_SERVICE \
# 	--add-cloudsql-instances $INSTANCE_CONNECTION_NAME \
# 	--update-env-vars INSTANCE_CONNECTION_NAME=$INSTANCE_CONNECTION_NAME,DB_PASS=$DB_PASS,DB_USER=$DB_USER,DB_NAME=$DB_NAME \
# 	--platform managed \
# 	--region asia-southeast1 \
# 	--allow-unauthenticated \
# 	--project=$GOOGLE_PROJECT_ID